create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL true [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_inst/inst/clk_out1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {flash_rom/datain_shift[0]} {flash_rom/datain_shift[1]} {flash_rom/datain_shift[2]} {flash_rom/datain_shift[3]} {flash_rom/datain_shift[4]} {flash_rom/datain_shift[5]} {flash_rom/datain_shift[6]} {flash_rom/datain_shift[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {flash_rom/read_data[0]} {flash_rom/read_data[1]} {flash_rom/read_data[2]} {flash_rom/read_data[3]} {flash_rom/read_data[4]} {flash_rom/read_data[5]} {flash_rom/read_data[6]} {flash_rom/read_data[7]} {flash_rom/read_data[8]} {flash_rom/read_data[9]} {flash_rom/read_data[10]} {flash_rom/read_data[11]} {flash_rom/read_data[12]} {flash_rom/read_data[13]} {flash_rom/read_data[14]} {flash_rom/read_data[15]} {flash_rom/read_data[16]} {flash_rom/read_data[17]} {flash_rom/read_data[18]} {flash_rom/read_data[19]} {flash_rom/read_data[20]} {flash_rom/read_data[21]} {flash_rom/read_data[22]} {flash_rom/read_data[23]} {flash_rom/read_data[24]} {flash_rom/read_data[25]} {flash_rom/read_data[26]} {flash_rom/read_data[27]} {flash_rom/read_data[28]} {flash_rom/read_data[29]} {flash_rom/read_data[30]} {flash_rom/read_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {flash_rom/sdo_count[0]} {flash_rom/sdo_count[1]} {flash_rom/sdo_count[2]} {flash_rom/sdo_count[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 5 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {flash_rom/state[0]} {flash_rom/state[1]} {flash_rom/state[2]} {flash_rom/state[3]} {flash_rom/state[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list flash_rom/cs_n_dbg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list flash_rom/sck]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list flash_rom/sdi_dbg]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 1 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list flash_rom/sdo_dbg]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk]
